version: "3"

services:
  db:
    hostname: guane
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=guane
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5050:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ".:/app"
    environment:
      - PSQL_HOST=guane
      - PSQL_USER=postgres
      - PSQ_PSSW=guane
      - PSQL_DB=postgres
    ports:
      - "5010:5010"
    depends_on:
      - db
