version: "3"

services:
  db:
    hostname: guane
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=guane
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5050:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ".:/app"
    environment:
      - PSQL_HOST=guane
      - PSQL_USER=postgres
      - PSQ_PSSW=guane
      - PSQL_DB=postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "5010:5010"
    depends_on:
      - db
      - redis

  worker:
    build: ./backend
    command: celery --app=backend.app.api.celery.worker.celery  worker  --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build: ./backend
    command:  celery flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
      - worker

